version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: ecommerce
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
  